### ISSUE TITLE
No cuda capable device is detected

### ISSUE THREAD

**Issue by LukyBruce** [moyix/fauxpilot#38]
Hi all,

My host is windows 10 with nivida 3090 +24gb vram， I cannot start triton container with error message not CUDA capable device is detected. Do You Know why? i can detect cuda with pytorch in the host.

=============================
== Triton Inference Server ==
=============================

NVIDIA Release 22.06 (build 39726160)
Triton Server Version 2.23.0

Copyright (c) 2018-2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

W0903 01:19:39.717609 88 pinned_memory_manager.cc:236] Unable to allocate pinned system memory, pinned memory pool will not be available: no CUDA-capable device is detected
I0903 01:19:39.717744 88 cuda_memory_manager.cc:115] CUDA memory pool disabled
E0903 01:19:39.753366 88 model_repository_manager.cc:2063] Poll failed for model directory 'codegen-16B-mono-1gpu': failed to open text file for read /model/codegen-16B-mono-1gpu/config.pbtxt: No such file or directory
E0903 01:19:39.773178 88 model_repository_manager.cc:2063] Poll failed for model directory 'codegen-16B-mono-2gpu': failed to open text file for read /model/codegen-16B-mono-2gpu/config.pbtxt: No such file or directory
E0903 01:19:39.795737 88 model_repository_manager.cc:2063] Poll failed for model directory 'codegen-16B-multi-1gpu': failed to open text file for read /model/codegen-16B-multi-1gpu/config.pbtxt: No such file or directory
E0903 01:19:39.815933 88 model_repository_manager.cc:2063] Poll failed for model directory 'codegen-16B-multi-2gpu': failed to open text file for read /model/codegen-16B-multi-2gpu/config.pbtxt: No such file or directory
E0903 01:19:39.836123 88 model_repository_manager.cc:2063] Poll failed for model directory 'codegen-16B-nl-1gpu': failed to open text file for read /model/codegen-16B-nl-1gpu/config.pbtxt: No such file or directory
E0903 01:19:39.857360 88 model_repository_manager.cc:2063] Poll failed for model directory 'codegen-16B-nl-2gpu': failed to open text file for read /model/codegen-16B-nl-2gpu/config.pbtxt: No such file or directory
E0903 01:19:39.881019 88 model_repository_manager.cc:2063] Poll failed for model directory 'codegen-2B-mono-1gpu': failed to open text file for read /model/codegen-2B-mono-1gpu/config.pbtxt: No such file or directory

**Comment by xinlnix** [comment]
Have you install nvidia on docker?

**Comment by LukyBruce** [comment]
> Have you install nvidia on docker?

No, isn't it already in the docker-compose file?

**Comment by LukyBruce** [comment]
after checking with the setup.sh and launch.sh, I may know the cause. Originally, I thought, docker-compose up would do everything.

**Comment by LukyBruce** [comment]
Issue has been solved. Fortunately, https://github.com/moyix/fauxpilot/issues/39 this helps me out of run fauxpilot in windows with docker.
